DROP TABLE IF EXISTS List_Movie;
DROP TABLE IF EXISTS Genre_Movie;
DROP TABLE IF EXISTS Subscription;
DROP TABLE IF EXISTS Lists;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Movies;
