version: '2'

services:
    app:
        build:
            context: ../
            dockerfile: docker/app/Dockerfile
        image: cs348-movielist-app-image
        container_name: cs348_movielist_app
        restart: always
        depends_on:
            - mysql
        volumes:
            - ../:/app
            - app_context:/context
        ports:
            - "5000:5000"
        environment:
            DATABASE_HOST: cs348_movielist_mysql
    mysql:
        image: mysql:8.0.25
        container_name: cs348_movielist_mysql
        restart: always
        expose:
            - '3306'
        ports:
            - "13306:3306"
        command: --secure-file-priv=
        environment:
            MYSQL_ROOT_PASSWORD: yolo
        volumes:
            - ../:/app
            - database:/var/lib/mysql
            - app_context:/context
volumes:
    app_context:
    database:
