version: '3'

services:
    app:
        build:
            context: ../
            dockerfile: docker/app/Dockerfile
        image: cs348-movielist-app-image
        container_name: cs348_movielist_app
        restart: always
        depends_on:
            - mysql
        volumes:
            - ../:/app
            - app_context:/context
        ports:
            - "5000:5000"
        environment:
            - USE_REAL_DATA
            - DATABASE_HOST=cs348_movielist_mysql
    mysql:
        image: mysql:8.0.25
        container_name: cs348_movielist_mysql
        restart: always
        expose:
            - '3306'
        ports:
            - "13306:3306"
        command: --secure-file-priv=
        environment:
            MYSQL_ROOT_PASSWORD: yolo
        volumes:
            - ../:/app
            - database:/var/lib/mysql
            - app_context:/context
    app-remote:
        build:
            context: ../
            dockerfile: docker/app/Dockerfile
        image: cs348-movielist-app-image
        container_name: cs348_movielist_app_remote
        restart: always
        profiles:
            - ignore
        volumes:
            - ../:/app
            - app_context:/context
        ports:
            - "5000:5000"
        entrypoint: ["bash", "-c", "cd /app/pyflask && flask run --host=0.0.0.0"]
        environment:
            - USE_REAL_DATA
            - DATABASE_HOST=burst.srv.vepta.org
            - DATABASE_PORT=13306
    from-snapshot:
        image: busybox:stable
        restart: "no"
        command: sh -c "cd / && wget 'https://public.s3.svc.vepta.org/school/database.tar.gz' && wget 'https://public.s3.svc.vepta.org/school/context.tar.gz' && rm -rf /database/* /context/* && tar -xzvf database.tar.gz && mv /vol/* /database/ && tar -xzvf context.tar.gz && mv /vol/* /context/"
        profiles:
            - ignore
        volumes:
            - database:/database
            - app_context:/context
volumes:
    app_context:
    database:
